--=======================================================
-- This code is generated by Brena Marques
--=======================================================
library ieee;
use ieee.std_logic_1164.all;
entity  is port(
	------------ CLOCK ----------
	CLOCK_50MHz	:in std_logic;
	CLK1_50	:in std_logic;,
	MAX10_CLK2_50	in std_logic;

	------------ SEG7 ----------
	DISP0_D		 		: out std_logic_vector(7 downto 0);
	DISP1_D		 		: out std_logic_vector(7 downto 0);

	------------ LED_MATRIX ----------
	LED_C		 		: out std_logic_vector(4 downto 0);
	LED_R		 		: out std_logic_vector(7 downto 0);

	------------ VGA ----------
	VGA_R		      		: out std_logic_vector(3 downto 0);
	VGA_G		      		: out std_logic_vector(3 downto 0);
	VGA_B		      		: out std_logic_vector(3 downto 0);
	VGA_HS		      		: out std_logic;
	VGA_VS		      		: out std_logic;
------------ SD_CARD ----------
	SD_CMD			: out std_logic;
	SD_CLK			: out std_logic;
	SD_CD_N			: out std_logic;
	SD_D			: inout std_logic_vector(3 downto 0);

------------ I2C ----------
	I2C_SDA			: inout std_logic;
	I2C_SCL			: out std_logic;
	I2C_OVERTEMP_N	: in std_logic;

------------ ETHERNET ----------
	ETH_TXEN		: out std_logic;
	ETH_TXD		: out std_logic_vector(3 downto 0);
	ETH_RXER		: in std_logic;
	ETH_RXDV		: in std_logic;
	ETH_RXD		: in std_logic_vector(3 downto 0);
	ETH_MDIO		: inout std_logic;
	ETH_MDC		: out std_logic;
	ETH_CRS		: in std_logic;
	ETH_COL		: in std_logic;
	ETH_RST_N		: out std_logic;
	ETH_RXCLK		: in std_logic;
	ETH_TXCLK		: in std_logic;
	ETH_TXER		: out std_logic;

------------ ADC ----------
	ADC_CNVST		: out std_logic;
	ADC_CS_N		: out std_logic;
	ADC_DOUT1		: in std_logic;
	ADC_DOUT2		: in std_logic;
	ADC_REFSEL		: out std_logic;
	ADC_SCLK		: out std_logic;
	ADC_SD			: out std_logic;
	ADC_SEL		: out std_logic;
	ADC_UB			: out std_logic;


	------------ DAC ----------
	DAC_CLR		          		: out std_logic;
	DAC_CS_N		      		: out std_logic;
	DAC_DIN		      		: out std_logic;
	DAC_SCLK		      		: out std_logic;

	------------ GPIO, GPIO connect to GPIO Default ----------
	GPIO_D		          		: inout std_logic_vector(35 downto 0)
);
end entity MERCURIO_IV_FULL;
architecture systembuilder of MERCURIO_IV_FULL is
--=======================================================

--  SIGNAL, CONSTANT, COMPONENT, FUNCTION declarations
--=======================================================
begin
--=======================================================
--  Structural coding
--=======================================================


end architecture systembuilder;
