//=======================================================
// This code is generated by Brena Marques
//=======================================================
module TESTE(
	//////////// CLOCK ////////////
input				CLOCK_50MHz,
input				CLOCK1_50MHz,

//////////// SEG7 //////////
output	[7:0]	DISP0_D,
output	[7:0]	DISP1_D,

//////////// LED_MATRIX //////////
output	[4:0]	LEDM_C,
output	[7:0]	LEDM_R,

//////////// VGA //////////
output	[3:0]	VGA_R,
output	[3:0]	VGA_G,
output	[3:0]	VGA_B,
output				VGA_HS,
output				VGA_VS,

//////////// SD_CARD //////////
output				SD_CMD,
output				SD_CLK,
output				SD_CD_N,
inout	[3:0]	SD_D,

//////////// I2C //////////
inout				I2C_SDA,
output				I2C_SCL,
input				I2C_OVERTEMP_N, //?

//////////// ETHERNET //////////
output				ETH_TXEN,
output				ETH_TXEN,
output	[3:0]	ETH_TXD,
input				ETH_RXER,
input				ETH_RXDV,
input	[3:0]	ETH_RXD,
inout				ETH_MDIO,
output				ETH_MDC,
input				ETH_CRS,
input				ETH_COL,
output				ETH_RST_N,
input				ETH_RXCLK,
input				ETH_TXCLK,
output				ETH_TXER,

//////////// ADC //////////
output				ADC_CNVST,
output				ADC_CS_N,
input				ADC_DOUT1,
input				ADC_DOUT2,
output				ADC_REFSEL,
output				ADC_SCLK,
output				ADC_SD,
output				ADC_SEL,
output				ADC_UB,

//////////// DAC //////////
output				DAC_CLR,
output				DAC_CS_N,
output				DAC_DIN,
output				DAC_SCLK,

//////////// GPIO, GPIO connect GPIO Default //////////
inout	[35:0]	GPIO_D,

);

//=======================================================
//  REG/WIRE declarations
//=======================================================




//=======================================================
//  Structural coding
//=======================================================




endmodule
