--=======================================================
-- This code is generated by Brena Marques
--=======================================================
library ieee;
use ieee.std_logic_1164.all;
entity VHDL is port(
	------------ CLOCK ----------
	ADC_CLK_1O	:in std_logic;
	MAX10_CLK1_50	:in std_logic;,
	MAX10_CLK2_50	in std_logic;

	------------ SEG7 ----------
	HEX0		 		: out std_logic_vector(7 downto 0);
	HEX1		 		: out std_logic_vector(7 downto 0);
	HEX2		 		: out std_logic_vector(7 downto 0);
	HEX3		 		: out std_logic_vector(7 downto 0);
	HEX4		 		: out std_logic_vector(7 downto 0);
	HEX5		 		: out std_logic_vector(7 downto 0);

	------------ LED ----------
	LEDR		 		: out std_logic_vector(9 downto 0);

	------------ VGA ----------
	VGA_R		      		: out std_logic_vector(3 downto 0);
	VGA_G		      		: out std_logic_vector(3 downto 0);
	VGA_B		      		: out std_logic_vector(3 downto 0);
	VGA_HS		      		: out std_logic;
	VGA_VS		      		: out std_logic;

	------------ Arduino ----------
	ARDUINO_IO		          		: inout std_logic_vector(15 downto 0);
	ARDUINO_RESET_N		      		: inout std_logic;
);
end entity DE10_LITE_FULL;

architecture systembuilder of DE10_LITE_FULL is
--=======================================================
--  SIGNAL, CONSTANT, COMPONENT, FUNCTION declarations
--=======================================================
begin
--=======================================================
--  Structural coding
--=======================================================


end architecture systembuilder;
