name: Build Windows Executable

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependências
        run: |
          pip install --upgrade pip
          pip install pipreqs pyinstaller
          pipreqs . --force
          pip install -r requirements.txt

      - name: Gerar executável com PyInstaller
        run: |
          pyinstaller --onefile main.py
        shell: cmd

      - name: Salvar executável como artifact
        uses: actions/upload-artifact@v4
        with:
          name: executavel-windows
          path: dist/*.exe
